config/routes.rb
Rails.application.routes.draw do
  devise_for :merchants, controllers: {
    passwords: 'merchants/passwords',
    registrations: 'merchants/registrations',
    sessions: 'merchants/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'merchants/orders#index'

  namespace :merchants do
    resource :orders, only: [:update]
    resources :orders, only: [] do
      put :confirm_order
      get :track
    end
  end

  get '/ready_to_ship' => 'merchants/orders#ready_to_ship'

  namespace :api do
    resource :orders, only: [:create] do
      post :geolocate
    end
  end
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :addresses, as: :addressable, dependent: :destroy
  has_many :orders, dependent: :destroy
  before_create :generate_api_token
  accepts_nested_attributes_for :addresses, allow_destroy: true

  validates :name, uniqueness: true
  validates :name, :phone_number, presence: true

  private

  def generate_api_token
    self.api_token = SecureRandom.hex(16).to_i(16).to_s(36)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  TYPES = ['Parcel', 'Satchel 1kg'].freeze
  COURIERS = ['Aramex', 'Ninja Van'].freeze

  belongs_to :merchant
  has_one :delivery, dependent: :destroy

  validates_presence_of :recipient, :recipient_address, :weight, :length, :width, :height
  validates :shipment_type,
    inclusion: { in: TYPES,
    message: "\"%{value}\" is not a valid shipment_type" },
    allow_nil: true,
    allow_blank: true
  validates :courier,
    inclusion: { in: COURIERS,
    message: "\"%{value}\" is not a valid courier" },
    allow_nil: true,
    allow_blank: true

  def has_valid_fields?
    validate_shipment_type
    validate_courier

    !self.errors.any?
  end

  private

  def validate_shipment_type
    self.errors.add(:base, 'Shipment Type is invalid') unless TYPES.include?(shipment_type)
  end

  def validate_courier
    self.errors.add(:base, 'Courier is invalid') unless COURIERS.include?(courier)
  end
end

app/controllers/api/orders_controller.rb
class Api::OrdersController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
  before_action :set_merchant, only: :create

  def create
    respond_to do |format|
      if @merchant
        OrderCreationWorker.perform_async(@merchant.id, order_params.to_json)
        format.json { render json: { status: '201 Order Accepted' }.to_json, status: :created }
      else
        format.json { render json: { status: '404 Not Found' }.to_json, status: :not_found }
      end
    end
  end

  def geolocate
    TrackShipmentWorker.perform_async(order_params[:id])
    order = Order.find(order_params[:id])

    respond_to do |format|
      if order.delivery
        format.json { render json: order.delivery.to_json, status: :accepted }
      else
        format.json { render json: { status: 'Failed to load' }.to_json, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_merchant
    @merchant = Merchant.find_by(api_token: request.headers['HTTP_API_TOKEN'])
  end

  def order_params
    params.fetch(:order).permit(%i[id recipient recipient_address weight length width height])
  end
end

app/controllers/merchants/orders_controller.rb
class Merchants::OrdersController < ApplicationController
  before_action :authenticate_merchant!
  before_action :set_order, only: :update

  def index
    @orders = current_merchant.orders.where('confirmed_at IS NULL')
                              .order('created_at DESC')
  end

  def ready_to_ship
    @orders = current_merchant.orders.where('confirmed_at NOT NULL')
                              .order('confirmed_at')
  end

  def track
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.js
      else
        format.js { render json: @order.errors.messages.to_json, status: :bad_request }
      end
    end
  end

  def confirm_order
    order = current_merchant.orders.find(params[:order_id])

    if params[:confirm] && order.has_valid_fields?
      ShipmentCreationWorker.perform_async(order.id)
      redirect_to root_path, notice: 'Order confirmation has started.'
    else
      redirect_to root_path, alert: order.errors.messages[:base].join(', ')
    end
  end

  private

  def set_order
    @order = current_merchant.orders.find(order_params[:id])
  end

  def order_params
    params.fetch(:order).permit(:id, :shipment_type, :courier)
  end
end

app/controllers/merchants/passwords_controller.rb
# frozen_string_literal: true

class Merchants::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/merchants/registrations_controller.rb
# frozen_string_literal: true

class Merchants::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number, addresses_attributes: [%i[country city postal_code street]]])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone_number])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/merchants/sessions_controller.rb
# frozen_string_literal: true

class Merchants::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/order_helper.rb
module OrderHelper
  def select_options_tag(name='',select_options={},options={})
    selected = ''
    unless options[:value].blank?
      selected = options[:value]
      options.delete(:value)
    end
    select_tag(name,options_for_select(select_options,selected),options)
  end
end

app/views/merchants/orders/index.html.erb
<div class="order-list">
  <h4>You currently have: <%= pluralize(@orders.count, 'order') %> awaiting confirmation.</h4>
  <div class="tabs">
    <%= link_to 'New Orders', root_path, class: 'active' %>
    <%= link_to 'Ready to Ship', ready_to_ship_path %>
    <a href="#">Track</a>
  </div>
  <table>
    <tr>
      <th><span class="arrow-down">▼</span> Recipient</th>
      <th><span class="arrow-down">▼</span> Type</th>
      <th><span class="arrow-down">▼</span> kg</th>
      <th><span class="arrow-down">▼</span> L(cm)</th>
      <th><span class="arrow-down">▼</span> W(cm)</th>
      <th><span class="arrow-down">▼</span> H(cm)</th>
      <th><span class="arrow-down">▼</span> Courier</th>
      <th><span class="arrow-down">▼</span></th>
    </tr>
    <% @orders.each do |order| %>
      <tr class="order" data-order='{"id": <%= order.id %>}'>
        <td><%= order.recipient %></td>
        <td>
          <%= select_options_tag(
            nil,
            [
              ['--select-type--', '', { "data-shipment": '{"shipment_type": ""}' }],
              ['Parcel', 'Parcel', { "data-shipment": '{"shipment_type": "Parcel"}' }],
              ['Satchel 1kg', 'Satchel 1kg', { "data-shipment": '{"shipment_type": "Satchel 1kg"}' }]
            ],
            value: order.shipment_type,
            class: 'shipment_type') %>
        </td>
        <td><%= order.weight %></td>
        <td><%= order.length %></td>
        <td><%= order.width %></td>
        <td><%= order.height %></td>
        <td>
          <%= select_options_tag(
            nil,
            [
              ['--select-courier--', '', { "data-shipment": '{"courier": ""}' }],
              ['Aramex', 'Aramex', { "data-shipment": '{"courier": "Aramex"}' }],
              ['Ninja Van', 'Ninja Van', { "data-shipment": '{"courier": "Ninja Van"}' }]
            ],
            value: order.courier,
            class: 'courier_type') %>
        </td>
        <td>
          <%= button_to 'Confirm',
            merchants_order_confirm_order_path(order.id),
            params: { confirm: true },
            method: :put %>
        </td>
      </tr>
    <% end %>
    <tr class="blank_row" height="36px">
      <td colspan="8"></td>
    </tr>
  </table>
</div>

app/views/merchants/orders/ready_to_ship.html.erb
<div class="order-list ready">
  <h4>
    You currently have:
    <%= pluralize(@orders.count, 'confirmed order') %>.</h4>
  <div class="tabs">
    <%= link_to 'New Orders', root_path %>
    <%= link_to 'Ready to Ship', ready_to_ship_path, class: 'active' %>
    <a href="#">Track</a>
  </div>
  <table>
    <tr>
      <th><span class="arrow-down">▼</span> Order Date</th>
      <th><span class="arrow-down">▼</span> Order Ref</th>
      <th><span class="arrow-down">▼</span> Recipient</th>
      <th><span class="arrow-down">▼</span> Courier</th>
      <th><span class="arrow-down">▼</span> Quote</th>
    </tr>
    <% @orders.each do |order| %>
      <tr class="order" data-order='{"id": <%= order.id %>}'>
        <td><%= order.confirmed_at.strftime("%e %b %I:%MPM") %></td>
        <td>
          <% if order.courier == 'Aramex' %>
          <%= button_to 'Track Order',
            merchants_order_track_path(order.id),
            method: :get %>
          <% else %>
            Not Available
          <% end %>
        </td>
        <td><%= order.recipient %></td>
        <td><%= order.courier %></td>
        <td><%= "$#{order.delivery.quote}" if order.delivery %></td>
      </tr>
    <% end %>
    <tr class="blank_row" height="36px">
      <td colspan="8"></td>
    </tr>
  </table>
</div>

app/views/merchants/orders/track.html.erb
<div class="order-list">
  <div class="tabs">
    <%= link_to 'New Orders', root_path %>
    <%= link_to 'Ready to Ship', ready_to_ship_path %>
    <a href="#" class="active">Track</a>
  </div>
  <div class="shipment">
    <div class="shipment-map">
      <div id="map"></div>
    </div>
    <div class="shipment-status">
      <div id="shipment-info"></div>
    </div>
    <div class="message">Loading Data...</div>
  </div>
</div>